version: "3.2"
services:
  nginx:
    image: "nginx:alpine"
    depends_on:
      - php
    ports:
      - target: 80
        published: 80
      - target: 443
        published: 443
    volumes:
      - ./src:/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params
      - ./log:/var/log/nginx
    command: [nginx-debug, "-g", "daemon off;"]
    deploy:
      mode: global
  php:
    image: "php:7.2-fpm-alpine"
    ports:
      - target: 9000
        published: 9000
    volumes:
      - ./php/php.ini:/usr/local/etc/php.ini
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./src:/var/www/html
      - ./log:/var/log
    deploy:
      mode: replicated
      replicas: 3
    # command: ["php", "-a"]
